config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # fake-admin
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # django admin
    path('this-is-admin-page/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),

    # local app
    path('', include('pages.urls')),
    path('proposal/', include('proposals.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),
]

proposals/urls.py
from django.urls import path
from .views import ProposalCreateView, ProposalDetailView

urlpatterns = [
    path('add/', ProposalCreateView.as_view(), name='proposal_add'),
    path('<int:pk>/', ProposalDetailView.as_view(), name='proposal_detail'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
from django.dispatch import receiver
from django.db import models

# Create your models here.
class CustomUser(AbstractUser):
    pass


@receiver(models.signals.post_save, sender=CustomUser)
def post_save_customuser_handler(sender, instance, created, **kwargs):
    """Add new user in mahasiswa group as default."""
    if created:
        group, group_created = Group.objects.get_or_create(name='mahasiswa')
        instance.groups.add(group)
        instance.save()

pages/models.py
from django.db import models

# Create your models here.

proposals/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone

CustomUser = get_user_model()


STATUS = (
    ('judul_submitted', 'Submit judul'),
    ('judul_approved', 'Judul approved'),
    ('proposal_submitted', 'Submit proposal'),
    ('proposal_revised', 'Submit revisi proposal'),
    ('proposal_dosen_ok', 'Proposal disetujui dosen pembimbing'),
    ('proposal_kaprodi_ok', 'Proposal disetujui kaprodi'),
    ('proposal_dosen_no', 'Proposal tidak disetujui dosen pembimbing'),
    ('proposal_kaprodi_no', 'Proposal tidak disetujui kaprodi'),
    ('proposal_approved', 'Proposal approved')
)


class Proposal(models.Model):
    mahasiswa = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE
    )
    judul = models.CharField(
        help_text='Judul Proposal.',
        blank=False,
        null=False,
        max_length=512,
    )

    def __str__(self):
        return f'Proposal {self.mahasiswa}'

    def get_absolute_url(self):
        return reverse('proposal_detail', args=(self.id,))


class Status(models.Model):
    proposal = models.ForeignKey(
        Proposal, on_delete=models.CASCADE
    )
    status = models.CharField(
        help_text='Status',
        choices=STATUS,
        max_length=100
    )
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.timestamp} - {self.get_status_display()}'

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutPageView(TemplateView):
    template_name = 'about.html'

proposals/views.py
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from proposals.models import Proposal, Status

class ProposalCreateView(CreateView):
    model = Proposal
    template_name = 'proposals/proposal_form.html'
    fields = ['judul']

    def form_valid(self, form):
        self.obj = form.save(commit=False)
        self.obj.mahasiswa = self.request.user
        self.obj.save()
        Status.objects.create(
            proposal=self.obj,
            status='Submit judul'
        )
        return super(ProposalCreateView, self).form_valid(form)


class ProposalDetailView(DetailView):
    model = Proposal
    template_name = 'proposals/proposal_detail.html'

proposals/templates/proposals/proposal_detail.html
{% extends '_base.html' %}
{% load static %}


{% block title %}Proposal Skripsi{% endblock title %}

{% block content %}
  <h1>Proposal Skripsi</h1>
  <ul>
    <li>Judul: {{ object.judul }}</li>
    <li>Pemohon: {{ object.mahasiswa.first_name }} {{ object.mahasiswa.last_name }}</li>
    <li>Status:
      <ul>
        {% for stat in object.status_set.all %}
          <li>{{ stat.status }}</li>
          <li>{{ stat.timestamp }}</li>
        {% endfor %}
      </ul>
    </li>
  </ul>

{% endblock %}

proposals/templates/proposals/proposal_form.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Proposal Skripsi{% endblock title %}

{% block content %}
  <h1>Submit Judul Proposal Skripsi</h1>
  <form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/_base.html
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Home{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <header>
    <!-- Fixed navbar-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <a href="{% url 'home' %}" class="navbar-brand my-0 mr-md-auto font-weight-normal">Home</a>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
        {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'proposal_add' %}">Submit Judul</a>
        <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
        <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
        {% endif %}
      </nav>
    </div>
  </header>
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
  <!-- JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
</body>
</html>

templates/about.html
{% extends '_base.html' %}

{% block title%}About{% endblock %}

{% block content %}
  <h1>About Page</h1>
{% endblock content%}

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
  <h1>Homepage</h1>
  <form class="form-inline mt-2 mt-md-0" action="" method="get">
    <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
  </form>
{% endblock %}